USE `supplychain_dev`;

-- Day03 采购模块表结构。
CREATE TABLE IF NOT EXISTS `purchase_requisition`
(
    `id` BIGINT UNSIGNED NOT NULL COMMENT '主键ID',
    `tenant_id` BIGINT NOT NULL COMMENT '租户ID',
    `req_no` VARCHAR(32) NOT NULL COMMENT '申请单编号',
    `req_source` TINYINT NOT NULL DEFAULT 3 COMMENT '需求来源：1库存预警 2销售预测 3人工申请',
    `title` VARCHAR(128) NOT NULL COMMENT '申请标题',
    `warehouse_id` BIGINT NOT NULL COMMENT '目标收货仓库ID',
    `expect_date` DATE NULL COMMENT '期望到货日期',
    `total_amount` DECIMAL(12, 2) NOT NULL DEFAULT 0.00 COMMENT '估算总金额',
    `priority` TINYINT NOT NULL DEFAULT 2 COMMENT '优先级：1紧急 2普通 3低',
    `status` TINYINT NOT NULL DEFAULT 0 COMMENT '状态：0草稿 1待审批 2通过 3拒绝 4已转采购单 5已取消',
    `approval_level` TINYINT NOT NULL DEFAULT 0 COMMENT '审批层级：0自动审批 1采购负责人 2财务负责人',
    `approval_role` VARCHAR(64) NULL COMMENT '审批角色：AUTO/PURCHASE_MANAGER/FINANCE_MANAGER',
    `apply_user_id` BIGINT NOT NULL COMMENT '申请人ID',
    `apply_user_name` VARCHAR(64) NOT NULL COMMENT '申请人姓名',
    `apply_time` DATETIME NOT NULL COMMENT '提交时间',
    `audit_user_id` BIGINT NULL COMMENT '审批人ID',
    `audit_time` DATETIME NULL COMMENT '审批时间',
    `audit_remark` VARCHAR(512) NULL COMMENT '审批意见',
    `remark` VARCHAR(512) NULL COMMENT '备注',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `create_by` BIGINT NULL COMMENT '创建人',
    `update_by` BIGINT NULL COMMENT '更新人',
    `is_deleted` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    `version` INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_tenant_req_no` (`tenant_id`, `req_no`),
    KEY `idx_tenant_status` (`tenant_id`, `status`),
    KEY `idx_apply_time` (`apply_time`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '采购申请单主表';

CREATE TABLE IF NOT EXISTS `purchase_requisition_item`
(
    `id` BIGINT UNSIGNED NOT NULL COMMENT '主键ID',
    `tenant_id` BIGINT NOT NULL COMMENT '租户ID',
    `req_id` BIGINT NOT NULL COMMENT '申请单ID',
    `sku_id` BIGINT NOT NULL COMMENT 'SKU ID',
    `sku_code` VARCHAR(64) NOT NULL COMMENT 'SKU编码',
    `sku_name` VARCHAR(256) NOT NULL COMMENT 'SKU名称',
    `quantity` INT NOT NULL COMMENT '采购数量',
    `current_stock` INT NOT NULL DEFAULT 0 COMMENT '当前库存快照',
    `safety_stock` INT NOT NULL DEFAULT 0 COMMENT '安全库存快照',
    `in_transit_qty` INT NOT NULL DEFAULT 0 COMMENT '在途库存快照',
    `ref_price` DECIMAL(10, 4) NULL COMMENT '参考单价',
    `expect_date` DATE NULL COMMENT '期望到货日期',
    `remark` VARCHAR(256) NULL COMMENT '备注',
    PRIMARY KEY (`id`),
    KEY `idx_req_id` (`req_id`),
    KEY `idx_sku_id` (`sku_id`),
    KEY `idx_tenant_id` (`tenant_id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '采购申请单明细表';

CREATE TABLE IF NOT EXISTS `purchase_inquiry`
(
    `id` BIGINT UNSIGNED NOT NULL COMMENT '主键ID',
    `tenant_id` BIGINT NOT NULL COMMENT '租户ID',
    `inquiry_no` VARCHAR(32) NOT NULL COMMENT '询价单编号',
    `req_id` BIGINT NULL COMMENT '采购申请单ID',
    `supplier_id` BIGINT NOT NULL COMMENT '供应商ID',
    `supplier_name` VARCHAR(128) NOT NULL COMMENT '供应商名称',
    `status` TINYINT NOT NULL DEFAULT 0 COMMENT '状态：0已发送 1已报价 2已选中 3未选中 4已过期',
    `send_time` DATETIME NOT NULL COMMENT '发送时间',
    `quote_deadline` DATETIME NULL COMMENT '报价截止时间',
    `quoted_time` DATETIME NULL COMMENT '回价时间',
    `response_hours` DECIMAL(8, 2) NULL COMMENT '响应小时数',
    `total_quote_amt` DECIMAL(12, 2) NULL COMMENT '总报价',
    `quote_valid_days` INT NULL COMMENT '报价有效天数',
    `quote_expire_date` DATE NULL COMMENT '报价到期日',
    `remark` VARCHAR(512) NULL COMMENT '询价备注',
    `supplier_remark` VARCHAR(512) NULL COMMENT '供应商备注',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `create_by` BIGINT NULL COMMENT '创建人',
    `is_deleted` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_tenant_inquiry_no` (`tenant_id`, `inquiry_no`),
    KEY `idx_req_id` (`req_id`),
    KEY `idx_supplier_id` (`supplier_id`),
    KEY `idx_tenant_status` (`tenant_id`, `status`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '询价单主表';

CREATE TABLE IF NOT EXISTS `purchase_inquiry_item`
(
    `id` BIGINT UNSIGNED NOT NULL COMMENT '主键ID',
    `tenant_id` BIGINT NOT NULL COMMENT '租户ID',
    `inquiry_id` BIGINT NOT NULL COMMENT '询价单ID',
    `sku_id` BIGINT NOT NULL COMMENT 'SKU ID',
    `sku_code` VARCHAR(64) NOT NULL COMMENT 'SKU编码',
    `sku_name` VARCHAR(256) NOT NULL COMMENT 'SKU名称',
    `inquiry_qty` INT NOT NULL COMMENT '询价数量',
    `quoted_price` DECIMAL(10, 4) NULL COMMENT '报价单价',
    `quoted_qty` INT NULL COMMENT '可供数量',
    `delivery_days` INT NULL COMMENT '交货天数',
    `min_order_qty` INT NULL COMMENT '最小起订量',
    `remark` VARCHAR(256) NULL COMMENT '备注',
    PRIMARY KEY (`id`),
    KEY `idx_inquiry_id` (`inquiry_id`),
    KEY `idx_sku_id` (`sku_id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '询价明细及供应商报价表';

CREATE TABLE IF NOT EXISTS `purchase_order`
(
    `id` BIGINT UNSIGNED NOT NULL COMMENT '主键ID',
    `tenant_id` BIGINT NOT NULL COMMENT '租户ID',
    `po_no` VARCHAR(32) NOT NULL COMMENT '采购单编号',
    `req_id` BIGINT NULL COMMENT '来源申请单ID',
    `inquiry_id` BIGINT NULL COMMENT '来源询价单ID',
    `supplier_id` BIGINT NOT NULL COMMENT '供应商ID',
    `supplier_name` VARCHAR(128) NOT NULL COMMENT '供应商名称',
    `warehouse_id` BIGINT NOT NULL COMMENT '仓库ID',
    `warehouse_name` VARCHAR(64) NOT NULL COMMENT '仓库名称',
    `total_amount` DECIMAL(12, 2) NOT NULL COMMENT '采购总金额',
    `tax_amount` DECIMAL(12, 2) NOT NULL DEFAULT 0.00 COMMENT '税额',
    `currency` CHAR(3) NOT NULL DEFAULT 'CNY' COMMENT '币种',
    `exchange_rate` DECIMAL(10, 6) NOT NULL DEFAULT 1.000000 COMMENT '汇率',
    `payment_type` TINYINT NOT NULL DEFAULT 1 COMMENT '付款方式',
    `payment_days` INT NOT NULL DEFAULT 0 COMMENT '账期天数',
    `paid_amount` DECIMAL(12, 2) NOT NULL DEFAULT 0.00 COMMENT '已付款金额',
    `order_date` DATE NOT NULL COMMENT '下单日期',
    `expected_date` DATE NULL COMMENT '期望到货日期',
    `confirmed_date` DATE NULL COMMENT '承诺到货日期',
    `actual_delivery_date` DATE NULL COMMENT '实际发货日期',
    `status` TINYINT NOT NULL DEFAULT 0 COMMENT '状态：0草稿 1待确认 2已确认 3发货中 4部分到货 5全部到货 6已对账 7已结清 8已取消',
    `logistics_company` VARCHAR(64) NULL COMMENT '物流公司',
    `tracking_no` VARCHAR(128) NULL COMMENT '物流单号',
    `contract_no` VARCHAR(64) NULL COMMENT '合同编号',
    `invoice_no` VARCHAR(64) NULL COMMENT '发票编号',
    `remark` VARCHAR(512) NULL COMMENT '备注',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `create_by` BIGINT NULL COMMENT '创建人',
    `update_by` BIGINT NULL COMMENT '更新人',
    `is_deleted` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    `version` INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_tenant_po_no` (`tenant_id`, `po_no`),
    KEY `idx_supplier_id` (`supplier_id`),
    KEY `idx_tenant_status` (`tenant_id`, `status`),
    KEY `idx_expected_date` (`expected_date`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '采购订单主表';

CREATE TABLE IF NOT EXISTS `purchase_order_item`
(
    `id` BIGINT UNSIGNED NOT NULL COMMENT '主键ID',
    `tenant_id` BIGINT NOT NULL COMMENT '租户ID',
    `po_id` BIGINT NOT NULL COMMENT '采购单ID',
    `sku_id` BIGINT NOT NULL COMMENT 'SKU ID',
    `sku_code` VARCHAR(64) NOT NULL COMMENT 'SKU编码',
    `sku_name` VARCHAR(256) NOT NULL COMMENT 'SKU名称',
    `spec` VARCHAR(256) NULL COMMENT '规格',
    `unit` VARCHAR(16) NOT NULL DEFAULT '件' COMMENT '单位',
    `quantity` INT NOT NULL COMMENT '采购数量',
    `received_qty` INT NOT NULL DEFAULT 0 COMMENT '已收货数量',
    `unit_price` DECIMAL(10, 4) NOT NULL COMMENT '单价',
    `amount` DECIMAL(12, 2) NOT NULL COMMENT '小计金额',
    `expect_date` DATE NULL COMMENT '期望到货日期',
    `remark` VARCHAR(256) NULL COMMENT '备注',
    PRIMARY KEY (`id`),
    KEY `idx_po_id` (`po_id`),
    KEY `idx_sku_id` (`sku_id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '采购订单明细表';

CREATE TABLE IF NOT EXISTS `purchase_receipt`
(
    `id` BIGINT UNSIGNED NOT NULL COMMENT '主键ID',
    `tenant_id` BIGINT NOT NULL COMMENT '租户ID',
    `receipt_no` VARCHAR(32) NOT NULL COMMENT '收货单编号',
    `po_id` BIGINT NOT NULL COMMENT '采购单ID',
    `po_no` VARCHAR(32) NOT NULL COMMENT '采购单编号',
    `supplier_id` BIGINT NOT NULL COMMENT '供应商ID',
    `warehouse_id` BIGINT NOT NULL COMMENT '仓库ID',
    `receive_date` DATE NOT NULL COMMENT '收货日期',
    `receiver_id` BIGINT NOT NULL COMMENT '收货人ID',
    `receiver_name` VARCHAR(64) NOT NULL COMMENT '收货人姓名',
    `status` TINYINT NOT NULL DEFAULT 0 COMMENT '状态：0待质检 1入库中 2部分入库 3全部入库 4拒收',
    `total_qty` INT NOT NULL DEFAULT 0 COMMENT '收货总数',
    `pass_qty` INT NOT NULL DEFAULT 0 COMMENT '合格数量',
    `reject_qty` INT NOT NULL DEFAULT 0 COMMENT '拒收数量',
    `is_on_time` TINYINT(1) NULL COMMENT '是否准时',
    `remark` VARCHAR(512) NULL COMMENT '备注',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `create_by` BIGINT NULL COMMENT '创建人',
    `update_by` BIGINT NULL COMMENT '更新人',
    `is_deleted` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    `version` INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_tenant_receipt_no` (`tenant_id`, `receipt_no`),
    KEY `idx_po_id` (`po_id`),
    KEY `idx_warehouse_id` (`warehouse_id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '采购收货单主表';

CREATE TABLE IF NOT EXISTS `purchase_receipt_item`
(
    `id` BIGINT UNSIGNED NOT NULL COMMENT '主键ID',
    `tenant_id` BIGINT NOT NULL COMMENT '租户ID',
    `receipt_id` BIGINT NOT NULL COMMENT '收货单ID',
    `po_item_id` BIGINT NOT NULL COMMENT '采购明细ID',
    `sku_id` BIGINT NOT NULL COMMENT 'SKU ID',
    `sku_code` VARCHAR(64) NOT NULL COMMENT 'SKU编码',
    `sku_name` VARCHAR(256) NOT NULL COMMENT 'SKU名称',
    `expected_qty` INT NOT NULL COMMENT '应到数量',
    `actual_qty` INT NOT NULL COMMENT '实收数量',
    `pass_qty` INT NOT NULL DEFAULT 0 COMMENT '合格数量',
    `reject_qty` INT NOT NULL DEFAULT 0 COMMENT '拒收数量',
    `reject_reason` VARCHAR(256) NULL COMMENT '拒收原因',
    `location_id` BIGINT NULL COMMENT '库位ID',
    `status` TINYINT NOT NULL DEFAULT 0 COMMENT '状态：0待质检 1已入库 2已退货',
    PRIMARY KEY (`id`),
    KEY `idx_receipt_id` (`receipt_id`),
    KEY `idx_po_item_id` (`po_item_id`),
    KEY `idx_sku_id` (`sku_id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '收货单明细表';

CREATE TABLE IF NOT EXISTS `purchase_return`
(
    `id` BIGINT UNSIGNED NOT NULL COMMENT '主键ID',
    `tenant_id` BIGINT NOT NULL COMMENT '租户ID',
    `return_no` VARCHAR(32) NOT NULL COMMENT '退货单编号',
    `po_id` BIGINT NOT NULL COMMENT '采购单ID',
    `po_no` VARCHAR(32) NOT NULL COMMENT '采购单编号',
    `supplier_id` BIGINT NOT NULL COMMENT '供应商ID',
    `warehouse_id` BIGINT NOT NULL COMMENT '仓库ID',
    `return_reason` TINYINT NOT NULL COMMENT '退货原因',
    `return_qty` INT NOT NULL COMMENT '退货数量',
    `return_amount` DECIMAL(12, 2) NOT NULL COMMENT '退货金额',
    `status` TINYINT NOT NULL DEFAULT 0 COMMENT '状态：0草稿 1已提交 2供应商确认 3已出库 4已收货 5完成 6拒绝',
    `handle_type` TINYINT NULL COMMENT '处理方式',
    `supplier_tracking_no` VARCHAR(128) NULL COMMENT '退货物流单号',
    `evidence_urls` JSON NULL COMMENT '证据附件',
    `remark` VARCHAR(512) NULL COMMENT '备注',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `create_by` BIGINT NULL COMMENT '创建人',
    `update_by` BIGINT NULL COMMENT '更新人',
    `is_deleted` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    `version` INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_tenant_return_no` (`tenant_id`, `return_no`),
    KEY `idx_po_id` (`po_id`),
    KEY `idx_supplier_id` (`supplier_id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '采购退货单表';
