-- ============================================================
-- Day06 TMS + 跨境合规建表脚本
-- ============================================================

CREATE TABLE IF NOT EXISTS `logistics_carrier`
(
    `id`              BIGINT UNSIGNED NOT NULL COMMENT '主键ID',
    `tenant_id`       BIGINT          NOT NULL COMMENT '租户ID',
    `carrier_code`    VARCHAR(32)     NOT NULL COMMENT '物流商编码',
    `carrier_name`    VARCHAR(64)     NOT NULL COMMENT '物流商名称',
    `carrier_name_en` VARCHAR(64)     NULL COMMENT '物流商英文名',
    `carrier_type`    TINYINT         NOT NULL COMMENT '物流商类型',
    `logo_url`        VARCHAR(512)    NULL COMMENT 'Logo地址',
    `api_base_url`    VARCHAR(256)    NULL COMMENT 'API基础地址',
    `api_key`         VARCHAR(256)    NULL COMMENT 'API Key',
    `api_secret`      VARCHAR(256)    NULL COMMENT 'API Secret',
    `api_account`     VARCHAR(128)    NULL COMMENT 'API账号',
    `api_version`     VARCHAR(16)     NULL COMMENT 'API版本',
    `track_api_url`   VARCHAR(256)    NULL COMMENT '轨迹API地址',
    `support_label`   TINYINT(1)      NOT NULL DEFAULT 1 COMMENT '是否支持面单',
    `support_track`   TINYINT(1)      NOT NULL DEFAULT 1 COMMENT '是否支持轨迹',
    `status`          TINYINT         NOT NULL DEFAULT 1 COMMENT '状态：0=停用 1=正常',
    `remark`          VARCHAR(512)    NULL COMMENT '备注',
    `create_time`     DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `update_time`     DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `create_by`       BIGINT          NULL,
    `update_by`       BIGINT          NULL,
    `is_deleted`      TINYINT(1)      NOT NULL DEFAULT 0,
    `version`         INT             NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_tenant_carrier_code` (`tenant_id`, `carrier_code`),
    KEY `idx_carrier_type` (`carrier_type`),
    KEY `idx_status` (`status`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '物流商主表';

CREATE TABLE IF NOT EXISTS `logistics_channel`
(
    `id`                   BIGINT UNSIGNED NOT NULL COMMENT '主键ID',
    `tenant_id`            BIGINT          NOT NULL COMMENT '租户ID',
    `carrier_id`           BIGINT          NOT NULL COMMENT '物流商ID',
    `channel_code`         VARCHAR(64)     NOT NULL COMMENT '渠道编码',
    `channel_name`         VARCHAR(128)    NOT NULL COMMENT '渠道名称',
    `channel_type`         TINYINT         NOT NULL COMMENT '渠道类型',
    `country_codes`        JSON            NOT NULL COMMENT '适用国家',
    `min_weight_g`         DECIMAL(10, 2)  NOT NULL DEFAULT 0 COMMENT '最小重量克',
    `max_weight_g`         DECIMAL(10, 2)  NOT NULL COMMENT '最大重量克',
    `max_length_mm`        INT             NULL COMMENT '最长边毫米',
    `max_girth_mm`         INT             NULL COMMENT '围长毫米',
    `allow_battery`        TINYINT(1)      NOT NULL DEFAULT 0 COMMENT '是否允许含电',
    `allow_liquid`         TINYINT(1)      NOT NULL DEFAULT 0 COMMENT '是否允许液体',
    `allow_powder`         TINYINT(1)      NOT NULL DEFAULT 0 COMMENT '是否允许粉末',
    `allow_food`           TINYINT(1)      NOT NULL DEFAULT 1 COMMENT '是否允许食品',
    `min_days`             DECIMAL(4, 1)   NOT NULL COMMENT '最短时效',
    `max_days`             DECIMAL(4, 1)   NOT NULL COMMENT '最长时效',
    `volume_factor`        INT             NOT NULL DEFAULT 5000 COMMENT '材积系数',
    `declared_value_limit` DECIMAL(12, 2)  NULL COMMENT '申报价值上限',
    `status`               TINYINT         NOT NULL DEFAULT 1 COMMENT '状态',
    `sort_order`           INT             NOT NULL DEFAULT 0 COMMENT '排序',
    `remark`               VARCHAR(512)    NULL COMMENT '备注',
    `create_time`          DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `update_time`          DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `create_by`            BIGINT          NULL,
    `update_by`            BIGINT          NULL,
    `is_deleted`           TINYINT(1)      NOT NULL DEFAULT 0,
    `version`              INT             NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_carrier_channel_code` (`carrier_id`, `channel_code`),
    KEY `idx_carrier_id` (`carrier_id`),
    KEY `idx_status` (`status`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '物流渠道表';

CREATE TABLE IF NOT EXISTS `logistics_rate`
(
    `id`                 BIGINT UNSIGNED NOT NULL COMMENT '主键ID',
    `tenant_id`          BIGINT          NOT NULL COMMENT '租户ID',
    `channel_id`         BIGINT          NOT NULL COMMENT '渠道ID',
    `country_code`       CHAR(2)         NOT NULL COMMENT '目的国',
    `zone`               VARCHAR(16)     NULL COMMENT '区域',
    `currency`           CHAR(3)         NOT NULL DEFAULT 'CNY' COMMENT '币种',
    `first_weight_g`     DECIMAL(10, 2)  NOT NULL COMMENT '首重克',
    `first_weight_price` DECIMAL(10, 4)  NOT NULL COMMENT '首重价格',
    `extra_weight_g`     DECIMAL(10, 2)  NOT NULL DEFAULT 500 COMMENT '续重克',
    `extra_weight_price` DECIMAL(10, 4)  NOT NULL COMMENT '续重价格',
    `min_charge`         DECIMAL(10, 4)  NOT NULL DEFAULT 0 COMMENT '最低收费',
    `fuel_rate`          DECIMAL(6, 4)   NOT NULL DEFAULT 0 COMMENT '燃油费率',
    `peak_rate`          DECIMAL(6, 4)   NOT NULL DEFAULT 0 COMMENT '旺季费率',
    `remote_area_fee`    DECIMAL(10, 4)  NOT NULL DEFAULT 0 COMMENT '偏远附加费',
    `effective_date`     DATE            NOT NULL COMMENT '生效日期',
    `expire_date`        DATE            NULL COMMENT '失效日期',
    `create_time`        DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `update_time`        DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `create_by`          BIGINT          NULL,
    `update_by`          BIGINT          NULL,
    `is_deleted`         TINYINT(1)      NOT NULL DEFAULT 0,
    `version`            INT             NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    KEY `idx_channel_country` (`channel_id`, `country_code`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '物流渠道费率表';

CREATE TABLE IF NOT EXISTS `logistics_waybill`
(
    `id`                  BIGINT UNSIGNED NOT NULL COMMENT '主键ID',
    `tenant_id`           BIGINT          NOT NULL COMMENT '租户ID',
    `waybill_no`          VARCHAR(32)     NOT NULL COMMENT '内部运单号',
    `tracking_no`         VARCHAR(128)    NULL COMMENT '物流商运单号',
    `carrier_id`          BIGINT          NOT NULL COMMENT '物流商ID',
    `channel_id`          BIGINT          NOT NULL COMMENT '渠道ID',
    `order_id`            BIGINT          NOT NULL COMMENT '订单ID',
    `order_no`            VARCHAR(32)     NOT NULL COMMENT '订单号',
    `warehouse_id`        BIGINT          NOT NULL COMMENT '仓库ID',
    `receiver_name`       VARCHAR(128)    NOT NULL COMMENT '收件人',
    `receiver_phone`      VARCHAR(32)     NULL COMMENT '电话',
    `country_code`        CHAR(2)         NOT NULL COMMENT '目的国',
    `state`               VARCHAR(64)     NULL COMMENT '州省',
    `city`                VARCHAR(64)     NULL COMMENT '城市',
    `address_line1`       VARCHAR(256)    NOT NULL COMMENT '地址1',
    `address_line2`       VARCHAR(256)    NULL COMMENT '地址2',
    `zip_code`            VARCHAR(16)     NOT NULL COMMENT '邮编',
    `actual_weight_g`     DECIMAL(10, 2)  NOT NULL COMMENT '实际重量',
    `volume_weight_g`     DECIMAL(10, 2)  NULL COMMENT '材积重',
    `charge_weight_g`     DECIMAL(10, 2)  NOT NULL COMMENT '计费重量',
    `length_mm`           INT             NULL COMMENT '长度',
    `width_mm`            INT             NULL COMMENT '宽度',
    `height_mm`           INT             NULL COMMENT '高度',
    `package_count`       INT             NOT NULL DEFAULT 1 COMMENT '包裹数',
    `declared_value`      DECIMAL(12, 2)  NOT NULL COMMENT '申报价值',
    `declared_currency`   CHAR(3)         NOT NULL DEFAULT 'USD' COMMENT '申报币种',
    `declared_name_en`    VARCHAR(256)    NOT NULL COMMENT '英文申报名',
    `hs_code`             VARCHAR(16)     NULL COMMENT 'HS编码',
    `is_gift`             TINYINT(1)      NOT NULL DEFAULT 0 COMMENT '是否礼品',
    `estimated_fee`       DECIMAL(12, 2)  NOT NULL DEFAULT 0 COMMENT '预估运费',
    `actual_fee`          DECIMAL(12, 2)  NULL COMMENT '实际运费',
    `fee_currency`        CHAR(3)         NOT NULL DEFAULT 'CNY' COMMENT '运费币种',
    `status`              TINYINT         NOT NULL DEFAULT 0 COMMENT '状态',
    `label_url`           VARCHAR(512)    NULL COMMENT '面单地址',
    `label_format`        VARCHAR(8)      NULL COMMENT '面单格式',
    `create_waybill_time` DATETIME        NULL COMMENT '创建运单时间',
    `pickup_time`         DATETIME        NULL COMMENT '揽收时间',
    `signed_time`         DATETIME        NULL COMMENT '签收时间',
    `exception_desc`      VARCHAR(512)    NULL COMMENT '异常描述',
    `create_time`         DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `update_time`         DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `create_by`           BIGINT          NULL,
    `update_by`           BIGINT          NULL,
    `is_deleted`          TINYINT(1)      NOT NULL DEFAULT 0,
    `version`             INT             NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_tenant_waybill_no` (`tenant_id`, `waybill_no`),
    UNIQUE KEY `uk_tracking_no` (`tracking_no`),
    UNIQUE KEY `uk_tenant_order_id` (`tenant_id`, `order_id`),
    KEY `idx_order_id` (`order_id`),
    KEY `idx_status` (`status`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '物流运单主表';

CREATE TABLE IF NOT EXISTS `logistics_track`
(
    `id`               BIGINT UNSIGNED NOT NULL COMMENT '主键ID',
    `tenant_id`        BIGINT          NOT NULL COMMENT '租户ID',
    `waybill_id`       BIGINT          NOT NULL COMMENT '运单ID',
    `tracking_no`      VARCHAR(128)    NOT NULL COMMENT '物流商运单号',
    `track_code`       VARCHAR(64)     NULL COMMENT '轨迹编码',
    `track_stage`      TINYINT         NOT NULL COMMENT '轨迹阶段',
    `raw_status`       VARCHAR(128)    NULL COMMENT '原始状态',
    `status_desc`      VARCHAR(256)    NOT NULL COMMENT '中文状态',
    `location`         VARCHAR(256)    NULL COMMENT '位置',
    `location_country` CHAR(2)         NULL COMMENT '位置国家',
    `track_time`       DATETIME        NOT NULL COMMENT '轨迹时间',
    `fetch_time`       DATETIME        NOT NULL COMMENT '抓取时间',
    `is_exception`     TINYINT(1)      NOT NULL DEFAULT 0 COMMENT '是否异常',
    `exception_type`   TINYINT         NULL COMMENT '异常类型',
    `exception_desc`   VARCHAR(512)    NULL COMMENT '异常描述',
    PRIMARY KEY (`id`),
    KEY `idx_waybill_id` (`waybill_id`),
    KEY `idx_tracking_no` (`tracking_no`),
    KEY `idx_is_exception` (`is_exception`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '物流轨迹记录表';

CREATE TABLE IF NOT EXISTS `logistics_fee_record`
(
    `id`               BIGINT UNSIGNED NOT NULL COMMENT '主键ID',
    `tenant_id`        BIGINT          NOT NULL COMMENT '租户ID',
    `waybill_id`       BIGINT          NOT NULL COMMENT '运单ID',
    `waybill_no`       VARCHAR(32)     NOT NULL COMMENT '运单号',
    `base_fee`         DECIMAL(12, 4)  NOT NULL DEFAULT 0 COMMENT '基础运费',
    `fuel_surcharge`   DECIMAL(12, 4)  NOT NULL DEFAULT 0 COMMENT '燃油附加费',
    `peak_surcharge`   DECIMAL(12, 4)  NOT NULL DEFAULT 0 COMMENT '旺季附加费',
    `remote_fee`       DECIMAL(12, 4)  NOT NULL DEFAULT 0 COMMENT '偏远费',
    `oversize_fee`     DECIMAL(12, 4)  NOT NULL DEFAULT 0 COMMENT '超尺寸费',
    `insurance_fee`    DECIMAL(12, 4)  NOT NULL DEFAULT 0 COMMENT '保价费',
    `other_fee`        DECIMAL(12, 4)  NOT NULL DEFAULT 0 COMMENT '其他费',
    `estimated_total`  DECIMAL(12, 2)  NOT NULL DEFAULT 0 COMMENT '预估总费用',
    `actual_total`     DECIMAL(12, 2)  NULL COMMENT '实际总费用',
    `currency`         CHAR(3)         NOT NULL DEFAULT 'CNY' COMMENT '币种',
    `billing_weight_g` DECIMAL(10, 2)  NOT NULL COMMENT '计费重量',
    `rate_id`          BIGINT          NULL COMMENT '费率ID',
    `create_time`      DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `update_time`      DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_waybill_id` (`waybill_id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '运单费用记录表';

CREATE TABLE IF NOT EXISTS `logistics_bill_record`
(
    `id`                 BIGINT UNSIGNED NOT NULL COMMENT '主键ID',
    `tenant_id`          BIGINT          NOT NULL COMMENT '租户ID',
    `bill_batch_no`      VARCHAR(32)     NOT NULL COMMENT '账单导入批次号',
    `carrier_code`       VARCHAR(32)     NOT NULL COMMENT '物流商编码',
    `waybill_id`         BIGINT          NULL COMMENT '匹配到的系统运单ID',
    `payable_id`         BIGINT          NULL COMMENT '财务应付账款ID',
    `waybill_no`         VARCHAR(32)     NULL COMMENT '内部运单号',
    `tracking_no`        VARCHAR(128)    NULL COMMENT '物流商运单号',
    `billing_weight_g`   DECIMAL(10, 2)  NULL COMMENT '账单计费重量',
    `base_fee`           DECIMAL(12, 4)  NOT NULL DEFAULT 0 COMMENT '基础运费',
    `fuel_surcharge`     DECIMAL(12, 4)  NOT NULL DEFAULT 0 COMMENT '燃油附加费',
    `peak_surcharge`     DECIMAL(12, 4)  NOT NULL DEFAULT 0 COMMENT '旺季附加费',
    `remote_fee`         DECIMAL(12, 4)  NOT NULL DEFAULT 0 COMMENT '偏远费',
    `other_fee`          DECIMAL(12, 4)  NOT NULL DEFAULT 0 COMMENT '其他费用',
    `actual_total`       DECIMAL(12, 2)  NOT NULL DEFAULT 0 COMMENT '账单实际总费用',
    `currency`           CHAR(3)         NOT NULL DEFAULT 'CNY' COMMENT '币种',
    `diff_amount`        DECIMAL(12, 2)  NOT NULL DEFAULT 0 COMMENT '实际费用与预估费用差异金额',
    `diff_rate`          DECIMAL(8, 4)   NOT NULL DEFAULT 0 COMMENT '费用差异率',
    `reconcile_status`   TINYINT         NOT NULL COMMENT '对账状态：0=自动通过 1=待人工复核 2=未匹配',
    `confirm_time`       DATETIME        NULL COMMENT '账单确认时间',
    `remark`             VARCHAR(512)    NULL COMMENT '对账备注',
    `create_time`        DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `update_time`        DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `idx_batch_no` (`tenant_id`, `bill_batch_no`),
    KEY `idx_tracking_no` (`tracking_no`),
    KEY `idx_reconcile_status` (`reconcile_status`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '物流商账单导入对账记录表';

CREATE TABLE IF NOT EXISTS `logistics_return`
(
    `id`                  BIGINT UNSIGNED NOT NULL COMMENT '主键ID',
    `tenant_id`           BIGINT          NOT NULL COMMENT '租户ID',
    `return_no`           VARCHAR(32)     NOT NULL COMMENT '退货单号',
    `original_waybill_id` BIGINT          NULL COMMENT '原运单ID',
    `order_id`            BIGINT          NOT NULL COMMENT '订单ID',
    `refund_id`           BIGINT          NULL COMMENT '退款单ID',
    `return_type`         TINYINT         NOT NULL COMMENT '退货类型',
    `carrier_id`          BIGINT          NULL COMMENT '物流商ID',
    `return_tracking_no`  VARCHAR(128)    NULL COMMENT '退货运单号',
    `from_country`        CHAR(2)         NOT NULL COMMENT '来源国',
    `to_warehouse_id`     BIGINT          NULL COMMENT '目标仓库',
    `status`              TINYINT         NOT NULL DEFAULT 0 COMMENT '状态',
    `expected_arrive_date` DATE           NULL COMMENT '预计到仓',
    `actual_arrive_date`   DATE           NULL COMMENT '实际到仓',
    `label_url`           VARCHAR(512)    NULL COMMENT '退货面单',
    `remark`              VARCHAR(512)    NULL COMMENT '备注',
    `create_time`         DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `update_time`         DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `create_by`           BIGINT          NULL,
    `update_by`           BIGINT          NULL,
    `is_deleted`          TINYINT(1)      NOT NULL DEFAULT 0,
    `version`             INT             NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_tenant_return_no` (`tenant_id`, `return_no`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '退货运单表';

CREATE TABLE IF NOT EXISTS `tax_vat_rate`
(
    `id`             BIGINT UNSIGNED NOT NULL COMMENT '主键ID',
    `country_code`   CHAR(2)         NOT NULL COMMENT '国家代码',
    `country_name`   VARCHAR(64)     NOT NULL COMMENT '国家名称',
    `vat_rate`       DECIMAL(6, 4)   NOT NULL COMMENT 'VAT税率',
    `threshold_value` DECIMAL(12, 2) NULL COMMENT '免税门槛',
    `currency`       CHAR(3)         NOT NULL COMMENT '币种',
    `effective_date` DATE            NOT NULL COMMENT '生效日期',
    `expire_date`    DATE            NULL COMMENT '失效日期',
    `create_time`    DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `update_time`    DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `idx_country_code` (`country_code`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = 'VAT税率配置表';
